# Scratch

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [3]:
df.columns.tolist()

['Id',
 'SepalLengthCm',
 'SepalWidthCm',
 'PetalLengthCm',
 'PetalWidthCm',
 'Species']

Sample Dictionary

In [4]:
dict_example = {
    
    'Colorado' : 'Rockies',
    'Boston'   : 'Red Sox',
    'Minnesota': 'Twins',
    'Milwaukee': 'Brewers',
    'Seattle'  : 'Mariners'
  
}

In [5]:
dict_example

{'Colorado': 'Rockies',
 'Boston': 'Red Sox',
 'Minnesota': 'Twins',
 'Milwaukee': 'Brewers',
 'Seattle': 'Mariners'}

In [6]:
dict_iris = {
    
    'Id': 'Numeric sequence',
    'SepalLengthCm': 'Length of the sepal (in cm)',
    'SepalWidthCm': 'Width of the sepal (in cm)',
    'PetalLengthCm': 'Length of the petal (in cm)',
    'PetalWidthCm': 'Width of the petal (in cm)',
    'Species': 'Species name'

    }

In [7]:
dict_iris

{'Id': 'Numeric sequence',
 'SepalLengthCm': 'Length of the sepal (in cm)',
 'SepalWidthCm': 'Width of the sepal (in cm)',
 'PetalLengthCm': 'Length of the petal (in cm)',
 'PetalWidthCm': 'Width of the petal (in cm)',
 'Species': 'Species name'}

In [14]:
dict_iris.keys()

dict_keys(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species'])

In [15]:
list(dict_iris.keys())

['Id',
 'SepalLengthCm',
 'SepalWidthCm',
 'PetalLengthCm',
 'PetalWidthCm',
 'Species']

In [18]:
dict_iris.get('Id')

'Numeric sequence'

---

In [8]:
import streamlit as st

In [9]:
# Web Scraping

def load_data(year):
    url = "https://www.basketball-reference.com/leagues/NBA_" + str(year) + "_per_game.html"
    html = pd.read_html(url, header = 0)
    df = html[0]
    raw = df.drop(df[df.Age == 'Age'].index) # Deletes repeating headers in content
    raw = raw.fillna(0)
    playerstats = raw.drop(['Rk'], axis=1)
    return playerstats

In [10]:
playerstats = load_data(2002)

In [11]:
playerstats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Tariq Abdul-Wahad,SG,27,TOT,24,12,18.4,2.3,6.1,.374,...,.727,1.7,1.8,3.5,1.0,0.8,0.4,1.1,2.3,5.6
1,Tariq Abdul-Wahad,SG,27,DEN,20,12,20.9,2.8,7.3,.379,...,.750,2.0,2.0,3.9,1.1,0.9,0.5,1.2,2.6,6.8
2,Tariq Abdul-Wahad,SG,27,DAL,4,0,6.0,0.0,0.5,.000,...,.000,0.5,1.0,1.5,0.5,0.5,0.3,0.8,1.3,0.0
3,Shareef Abdur-Rahim,PF,25,ATL,77,77,38.7,7.8,16.8,.461,...,.801,2.6,6.5,9.0,3.1,1.3,1.1,3.2,2.8,21.2
4,Courtney Alexander,SG,24,WAS,56,28,23.7,4.0,8.5,.470,...,.810,0.8,1.9,2.6,1.5,0.6,0.1,1.1,2.0,9.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,Metta World Peace,SF,22,TOT,55,50,29.9,4.9,11.6,.423,...,.667,1.3,3.6,4.9,2.3,2.6,0.7,2.1,3.9,13.2
517,Metta World Peace,SF,22,CHI,27,26,30.5,5.6,13.0,.433,...,.628,1.5,3.4,4.9,2.9,2.8,0.9,2.6,4.0,15.6
518,Metta World Peace,SF,22,IND,28,24,29.3,4.2,10.2,.411,...,.733,1.2,3.8,5.0,1.8,2.4,0.6,1.8,3.9,10.9
519,Lorenzen Wright,C,26,MEM,43,33,29.1,5.2,11.3,.459,...,.569,3.0,6.4,9.4,1.0,0.7,0.5,1.7,2.9,12.0
520,Wang Zhizhi,C,24,DAL,55,0,10.9,2.0,4.5,.440,...,.737,0.3,1.7,2.0,0.4,0.2,0.3,0.5,1.5,5.6